version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: job-postgres
    environment:
      POSTGRES_USER: jobs
      POSTGRES_PASSWORD: jobs
      POSTGRES_DB: jobsdb
    ports:
      - "5432:5432"