spring.application.name=job-api
spring.datasource.url=jdbc:postgresql://localhost:5432/jobsdb
spring.datasource.username=jobs
spring.datasource.password=jobs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
